# test_config_cli.toml

# first reduce phase
[[reduce_phase]]
style = "normal"
type = "sync"
max_allowed_subproblem_size = 10 # vertices
# async only:
message_queue_local_threshold = 1000 # Bytes
[reduce_phase.initial_partitioning]
disable_partitioning = false
epsilon = 0.03 # max 3 percent imbalance
minimum_vertices_per_rank=10


# greedy solver
[greedy]
algo = "sync"
message_queue_local_threshold = 1000
[greedy.initial_partitioning]
disable_partitioning = true


