# test_config_cli.toml

# first reduce phase
[[reduce_phase]]
style = "normal"
type = "sync"
max_allowed_subproblem_size = 10 # vertices
# async only:
[reduce_phase.initial_partitioning]
disable_partitioning = true

# greedy solver
[greedy]
algo = "sync"
[greedy.initial_partitioning]
disable_partitioning = true


