name: Vendored release (with submodules)

on:
  release:
    types: [published]

permissions:
      contents: write
      packages: read

jobs:
  bundle-and-attach:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    container:
      image: ghcr.io/jabo17/kadisredu-reproducibility:main
      options: --user 0:0

    steps:
      - name: Checkout (include submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Prefetch FetchContent dependencies
        run: |
          cmake -S . -B build
          rm -rf build
          rm -rf _deps/*build

      - name: Show submodule SHAs (provenance)
        run: |
          echo "Submodule commit map:" > SUBMODULES.txt
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git submodule status --recursive >> SUBMODULES.txt
          cat .gitmodules >> SUBMODULES.txt

      - name: Create vendored tarball
        run: |
          RELEASE_NAME="${{ github.event.repository.name }}-${{ github.ref_name }}-with-dep"
          tar --exclude-vcs --exclude='.git' --exclude="$GITHUB_ENV" --exclude "${RELEASE_NAME}.tar.gz" -czf "../${RELEASE_NAME}.tar.gz" .
          echo "ARCHIVE_NAME=../${RELEASE_NAME}.tar.gz" >> $GITHUB_ENV
          
      - name: Attach vendored archive
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ARCHIVE_NAME }}
            SUBMODULES.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
